SELECT A.ANIMAL_ID, A.NAME
FROM (
    SELECT AO.ANIMAL_ID, AO.NAME, 
           DATEDIFF(AO.DATETIME, AI.DATETIME) AS PROTECTION_DAYS
    FROM ANIMAL_OUTS AO
    JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
) A
ORDER BY A.PROTECTION_DAYS DESC
LIMIT 2;
