SELECT 
    USED_GOODS_USER.USER_ID,
    USED_GOODS_USER.NICKNAME,
    CONCAT(USED_GOODS_USER.CITY, ' ', USED_GOODS_USER.STREET_ADDRESS1, ' ', USED_GOODS_USER.STREET_ADDRESS2) AS 전체주소,
    INSERT(INSERT(USED_GOODS_USER.TLNO, 4, 0, '-'), 9, 0, '-') AS 전화번호
FROM 
    USED_GOODS_USER
JOIN 
    USED_GOODS_BOARD 
ON 
    USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
GROUP BY 
    USED_GOODS_USER.USER_ID, 
    USED_GOODS_USER.NICKNAME, 
    전체주소, 
    전화번호
HAVING 
    COUNT(USED_GOODS_BOARD.BOARD_ID) >= 3
ORDER BY 
    USED_GOODS_USER.USER_ID DESC;
